import boardReducer from "./board-reducer";
import gameOverReducer from "./game-over-reducer";
import { combineReducers } from "redux";

const rootReducer = combineReducers({ 
    history: boardReducer,
    gameOver: gameOverReducer
  })

export default rootReducer;

// The reducer generated by combineReducers({ a, b }) looks like this:
// function combined(state = {}, action) {
//   return {
//     a: a(state.a, action),
//     b: b(state.b, action)
//   }
// }